### ISSUE TITLE
Auto-Update crashing Spotify 

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/BurntSushi#2]
Burnt sushi is crashing spotify.

**Comment by OpenByteDev** [comment]
You probably need to update spotify.
Currently BurntSushi causes spotify to crash when it tries to self update.

**Comment by ghost** [comment]
oh ok

**Comment by prorounak2005** [comment]
Burnt Sushi keeps Crashing Spotify Continuosly  . What should I do ?

**Comment by prorounak2005** [comment]
After the new update of spotify . The burnt sushi keeps crashing spotify continuosly.

**Comment by ghost** [comment]
> You probably need to update spotify.
> Currently BurntSushi causes spotify to crash when it tries to self update.

Ok So I searched how to disable spotify Auto Update and I got a spotify community discussion on how to disable Auto-Updates. So can I try this one ? - 
![image](https://user-images.githubusercontent.com/69617708/118085533-2f260880-b3e0-11eb-94c1-f993794bfa62.png)
I can create a batch file so that Every time I install new Spotify manually I can run the batch file which will stop spotify from auto updating ?

**Comment by ghost** [comment]
Link to the community post here - https://community.spotify.com/t5/Desktop-Windows/Stopping-Auto-update/td-p/4785101#:~:text=Creates%20directory%20C%3A%5CUsers,from%20removing%20it%20without%20admin   (1st Comment).

**Comment by OpenByteDev** [comment]
> 
> 
> > You probably need to update spotify.
> > Currently BurntSushi causes spotify to crash when it tries to self update.
> 
> Ok So I searched how to disable spotify Auto Update and I got a spotify community discussion on how to disable Auto-Updates. So can I try this one ? -
> ![image](https://user-images.githubusercontent.com/69617708/118085533-2f260880-b3e0-11eb-94c1-f993794bfa62.png)
> I can create a batch file so that Every time I install new Spotify manually I can run the batch file which will stop spotify from auto updating ?

sure you can?

**Comment by ghost** [comment]
Spotify is still crashing simultaneously. Please help.

**Comment by OpenByteDev** [comment]
> You probably need to update spotify.
> Currently BurntSushi causes spotify to crash when it tries to self update.

**Comment by OpenByteDev** [comment]
This should be fixed with 4bc203456134fb2a78ff026c37f1cd05af532eb2 in [v0.3.0](https://github.com/OpenByteDev/BurntSushi/releases/tag/0.3.0).
