### ISSUE TITLE
(Idea) Icon tray

### ISSUE THREAD

**Issue by sharkiller** [OpenByteDev/BurntSushi#9]
Since the app already log into a file in localappdata, can a parameter be added to not open a console and just be a tray icon to close the app?

**Comment by sharkiller** [comment]
if someone want an easy fix. Download Hidden Start (hstart) and create a shortcut with the gui to burntsushi and spotify.
Should get something like this:
`"C:\Program Files\Hidden Start\hstart64.exe" /NOCONSOLE "[path to-->]\BurntSushi.exe" "[path to-->]\Spotify.exe"`

and when run the shortcut, spotify open without ads and no burntsushi console.  
but to close burntsushi you need to close it from the task manager. 
a tray icon could be perfect solution to close the app even if no hide console is implemented.

**Comment by OpenByteDev** [comment]
Solved in rewrite: https://github.com/OpenByteDev/burnt-sushi
